name: Flutter Test
on: 
   push:
      branches:
         - master
   pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'
      - run: "flutter --version"
      - run: flutter pub get
      - run: flutter test
