name: Flutter Test
on:
   push:
      branches:
         - master
   pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'
      - run: 'flutter clean'
      - run: 'flutter --version'
      - run: 'flutter doctor -v'
      - run: 'git submodule update --init --recursive'
      - run: 'flutter pub get'
      - run: 'flutter gen-l10n'
      - run: 'flutter test'
