name: Flutter integration test
on: 
    push:
       branches:
          - master
    pull_request:
jobs:
    drive_android:
      runs-on: macos-latest
      strategy:
        matrix:
          api-level: [29]
          target: [playstore]
      steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: '3.13.2'
            channel: 'stable'
  
        # Run integration test
        - name: Run Flutter Driver tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            target: ${{ matrix.target }}
            api-level: ${{ matrix.api-level }}
            arch: x86_64
            profile: Nexus 6
            script: flutter test integration_test
  
